# Generated by Django 6.0.6 on 2026-06-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_dataresourcegroup_dataresource_inventory_group"),
        ("ecology", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomeAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="注释编号"
                    ),
                ),
                (
                    "annotation_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="注释类型"
                    ),
                ),
                (
                    "reference_version",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="参考版本"
                    ),
                ),
                (
                    "gene_count",
                    models.PositiveIntegerField(default=0, verbose_name="基因数量"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "基因组注释",
                "verbose_name_plural": "基因组注释",
                "ordering": ("annotation_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="GenomeAssembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assembly_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="组装编号"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=80, verbose_name="版本"),
                ),
                (
                    "assembly_level",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="组装级别"
                    ),
                ),
                (
                    "genome_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="基因组大小"
                    ),
                ),
                (
                    "contig_n50",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Contig N50"
                    ),
                ),
                (
                    "scaffold_n50",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Scaffold N50"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "基因组组装",
                "verbose_name_plural": "基因组组装",
                "ordering": ("assembly_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="GenomeDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genome_dataset_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="基因组数据集编号"
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="数据集名称")),
                (
                    "dataset_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="数据集类型"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="测序平台"
                    ),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=80, verbose_name="状态"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "基因组数据集",
                "verbose_name_plural": "基因组数据集",
                "ordering": ("genome_dataset_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="GenomeSequenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="基因组文件编号"
                    ),
                ),
                (
                    "file_role",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="文件角色"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="文件格式"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="存储路径"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, max_length=128, verbose_name="校验值"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "基因组序列文件",
                "verbose_name_plural": "基因组序列文件",
                "ordering": ("file_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="GermplasmAccession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accession_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="种质资源编号"
                    ),
                ),
                (
                    "sample_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="样品编号"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="材料类型"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="资源类型"
                    ),
                ),
                (
                    "sex",
                    models.CharField(blank=True, max_length=40, verbose_name="性别"),
                ),
                (
                    "is_core",
                    models.BooleanField(default=False, verbose_name="核心种质资源"),
                ),
                (
                    "storage_status",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="保存状态"
                    ),
                ),
                ("raw_location", models.TextField(blank=True, verbose_name="原始地点")),
                (
                    "raw_longitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始经度"
                    ),
                ),
                (
                    "raw_latitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始纬度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "种质资源",
                "verbose_name_plural": "种质资源",
                "ordering": ("accession_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="MolecularAssay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assay_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="实验编号"
                    ),
                ),
                (
                    "assay_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="实验类型"
                    ),
                ),
                (
                    "marker_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="标记名称"
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="批次编号"
                    ),
                ),
                (
                    "laboratory",
                    models.CharField(blank=True, max_length=160, verbose_name="实验室"),
                ),
                (
                    "assayed_on",
                    models.DateField(blank=True, null=True, verbose_name="实验日期"),
                ),
                (
                    "result_status",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="结果状态"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分子实验",
                "verbose_name_plural": "分子实验",
                "ordering": ("assay_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="MolecularFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="文件编号"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="文件类型"
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="文件格式"
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="存储路径"
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, max_length=128, verbose_name="校验值"),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "分子数据文件",
                "verbose_name_plural": "分子数据文件",
                "ordering": ("file_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="MolecularResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="结果编号"
                    ),
                ),
                (
                    "locus",
                    models.CharField(blank=True, max_length=120, verbose_name="位点"),
                ),
                (
                    "allele",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="等位基因"
                    ),
                ),
                (
                    "value_text",
                    models.CharField(blank=True, max_length=255, verbose_name="文本值"),
                ),
                (
                    "value_numeric",
                    models.FloatField(blank=True, null=True, verbose_name="数值"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                (
                    "quality_flag",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="质控标记"
                    ),
                ),
            ],
            options={
                "verbose_name": "分子实验结果",
                "verbose_name_plural": "分子实验结果",
                "ordering": ("assay_id", "id"),
            },
        ),
        migrations.CreateModel(
            name="MolecularSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "molecular_sample_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="分子样品编号"
                    ),
                ),
                (
                    "nucleic_acid_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="核酸类型"
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="提取方法"
                    ),
                ),
                (
                    "concentration",
                    models.FloatField(blank=True, null=True, verbose_name="浓度"),
                ),
                (
                    "purity_260_280",
                    models.FloatField(blank=True, null=True, verbose_name="260/280"),
                ),
                (
                    "storage_condition",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="保存条件"
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提取时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "分子样品",
                "verbose_name_plural": "分子样品",
                "ordering": ("molecular_sample_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="SequencingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="测序批次编号"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="测序平台"
                    ),
                ),
                (
                    "library_strategy",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="文库策略"
                    ),
                ),
                (
                    "read_length",
                    models.PositiveIntegerField(default=0, verbose_name="读长"),
                ),
                (
                    "read_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="读数"),
                ),
                (
                    "run_date",
                    models.DateField(blank=True, null=True, verbose_name="测序日期"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
            ],
            options={
                "verbose_name": "测序批次",
                "verbose_name_plural": "测序批次",
                "ordering": ("run_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="VariantDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="变异集编号"
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="变异类型"
                    ),
                ),
                (
                    "reference_assembly",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="参考组装"
                    ),
                ),
                (
                    "variant_count",
                    models.PositiveBigIntegerField(default=0, verbose_name="变异数量"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "变异数据集",
                "verbose_name_plural": "变异数据集",
                "ordering": ("variant_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="BiologicalSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_code",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="样品编号"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="材料类型"
                    ),
                ),
                (
                    "sex",
                    models.CharField(blank=True, max_length=40, verbose_name="性别"),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="采集时间"
                    ),
                ),
                (
                    "collector",
                    models.CharField(blank=True, max_length=120, verbose_name="采集人"),
                ),
                ("raw_location", models.TextField(blank=True, verbose_name="原始地点")),
                (
                    "raw_longitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始经度"
                    ),
                ),
                (
                    "raw_latitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始纬度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biological_samples",
                        to="ecology.individualorganism",
                        verbose_name="个体",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biological_samples",
                        to="ecology.populationunit",
                        verbose_name="种群",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biological_samples",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biological_samples",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "生物样品",
                "verbose_name_plural": "生物样品",
                "ordering": ("sample_code", "id"),
            },
        ),
    ]
