name: geomanager
channels:
  - conda-forge
dependencies:
  - django
  - fiona
  - gdal
  - geopandas
  - gunicorn
  - libgdal-arrow-parquet
  - numba
  - openpyxl
  - pandas
  - pillow
  - pip
  - pyarrow
  - pytest
  - pytest-django
  - python=3.14
  - rasterio
  - ruff
  - tomlkit
  - whitenoise
  - xlrd
