/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bootstrap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取系统启动配置
         * @description 获取前端应用初始化所需的全局配置信息
         */
        get: operations["getBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取 CSRF Cookie
         * @description 设置 csrftoken Cookie，后续所有非 GET 请求需读取此 Cookie 值
         */
        get: operations["getCsrfCookie"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 注册新用户。首个注册的用户将自动成为系统管理员。
         *     注册功能受系统配置 `allowRegistration` 控制。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登出 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/directories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取数据目录树
         * @description 返回所有已激活的数据目录及其关联的数据资源
         */
        get: operations["getDirectories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/resources/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取数据资源列表
         * @description 支持多条件筛选的数据资源分页列表
         */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/scan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 扫描数据源
         * @description 触发一次数据目录源扫描，发现并同步新的数据资源
         */
        post: operations["scanCatalogSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/import/preview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 导入数据预检
         * @description 解析上传的 Excel/CSV 第一张表，按文本读取字段，自动推测经纬度列，
         *     并返回样例行和字段列表。该接口不执行坐标数据校验，不写入数据。
         */
        post: operations["importPreview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/import/validate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传数据校验
         * @description 按当前表单选择的导入类型和经纬度列校验上传文件，不写入数据
         */
        post: operations["importValidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/import/commit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 提交数据导入
         * @description 将预检后的 Excel/CSV 导入统一存储。选择地理数据时写入 GeoPackage，
         *     选择非地理数据时写入 SQLite。接口会同步创建或更新 DataResource。
         */
        post: operations["importCommit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/resources/{id}/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取数据资源详情
         * @description 获取指定数据资源的元数据、字段信息及空间范围
         */
        get: operations["getResourceProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/resources/{id}/query/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询矢量数据
         * @description 对矢量数据资源执行属性 + 空间联合查询，返回 GeoJSON FeatureCollection
         */
        post: operations["queryResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/export/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 同步导出图层
         * @description 将指定图层数据导出为 ZIP 文件（含 Shapefile 或 GeoTIFF）
         */
        post: operations["exportLayers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/export/async/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 异步导出图层
         * @description 与同步导出参数相同，但以异步任务方式执行
         */
        post: operations["exportLayersAsync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/export/jobs/{job_id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载导出文件 */
        get: operations["downloadExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取图层列表 */
        get: operations["getLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{layer_name}/features/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取图层 GeoJSON 要素
         * @description 获取矢量图层的全部要素（GeoJSON FeatureCollection 格式）。
         *     返回前会忽略无几何、经度越界、纬度越界的数据，相关警告通过 `warnings` 字段返回。
         */
        get: operations["getLayerFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{layer_name}/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取统一 GeoPackage 矢量图层详情
         * @description 获取未登记为 DataResource 的 GeoPackage 图层元数据、字段信息及空间范围
         */
        get: operations["getLayerProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/{layer_name}/query/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询统一 GeoPackage 矢量图层
         * @description 对未登记为 DataResource 的 GeoPackage 图层执行属性 + 空间联合查询
         */
        post: operations["queryLayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/achievements/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取成果列表 */
        get: operations["getAchievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全局搜索
         * @description 同时搜索数据资源和研究成果。`q` 为空时返回空结果。
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/datasets/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取栅格数据集列表 */
        get: operations["getRasterDatasets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入栅格文件 */
        post: operations["importRaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/scan/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 扫描栅格源目录
         * @description 扫描研究数据目录中的未处理栅格文件，自动创建数据集
         */
        post: operations["scanRasterSources"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/render/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册栅格渲染样式（同步）
         * @description 为栅格图层注册瓦片样式并返回 XYZ 瓦片 URL
         */
        post: operations["renderRaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/render/async/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 异步注册栅格渲染样式 */
        post: operations["renderRasterAsync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/unique-values/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 获取栅格唯一值分类
         * @description 获取指定栅格数据集某一波段的唯一值列表，用于唯一值符号化
         */
        post: operations["getUniqueValues"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/jobs/{job_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询异步任务状态
         * @description 所有异步操作（栅格导入、扫描、渲染、导出）均返回统一的任务对象
         */
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/raster/tiles/{dataset_id}/{style_hash}/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取 XYZ 瓦片
         * @description 获取渲染后的栅格 PNG 瓦片，供 Mapbox GL JS 消费
         */
        get: operations["getTile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description 错误描述信息 */
            detail: string;
        };
        DetailResponse: {
            /** @description 操作结果说明 */
            detail: string;
        };
        BootstrapResponse: {
            /**
             * @description 系统显示名称
             * @example 中亚胡杨林生态系统保护数据共享平台
             */
            systemName: string;
            /**
             * @description 是否允许用户自助注册
             * @example true
             */
            allowRegistration: boolean;
            map: components["schemas"]["MapConfig"];
            limits: components["schemas"]["SystemLimits"];
        };
        MapConfig: {
            /**
             * @description 默认地图中心点，经纬度顺序为 [longitude, latitude]
             * @example [
             *       87.6,
             *       41.7
             *     ]
             */
            defaultCenter: [
                number,
                number
            ];
            /**
             * @description 默认地图缩放级别
             * @example 6.5
             */
            defaultZoom: number;
            /**
             * @description 默认 Mapbox 底图样式
             * @example mapbox://styles/mapbox/satellite-streets-v12
             */
            defaultBasemap: string;
            /** @description 前端加载 Mapbox 服务所需 token */
            mapboxAccessToken: string;
        };
        SystemLimits: {
            /**
             * @description 单次上传文件大小上限，单位 MB
             * @example 500
             */
            uploadMaxMb: number;
            /**
             * @description 单次查询返回结果上限
             * @example 30000
             */
            queryResultLimit: number;
        };
        HealthResponse: {
            /**
             * @description 服务健康状态
             * @example ok
             */
            status: string;
            /**
             * @description TOML 配置是否已加载
             * @example true
             */
            configLoaded: boolean;
            /** @description 业务数据根目录下固定子目录 */
            appSubdirs: string[];
            /** @description 科研数据根目录下固定子目录 */
            researchSubdirs: string[];
        };
        LoginRequest: {
            /** @description 用户名 */
            username: string;
            /**
             * Format: password
             * @description 密码
             */
            password: string;
            /**
             * @description 是否使用持久会话
             * @default false
             */
            remember?: boolean;
        };
        LoginResponse: {
            user: components["schemas"]["UserInfo"];
        };
        RegisterRequest: {
            /** @description 用户名（唯一） */
            username: string;
            /**
             * Format: email
             * @description 邮箱
             */
            email?: string;
            /**
             * Format: password
             * @description 密码
             */
            password: string;
            /**
             * Format: password
             * @description 确认密码
             */
            passwordConfirm: string;
        };
        RegisterResponse: {
            user: components["schemas"]["UserInfo"];
            /** @description 注册结果说明 */
            detail: string;
        };
        UserInfoResponse: {
            /**
             * @description 当前请求是否已认证
             * @example true
             */
            authenticated: boolean;
            user: components["schemas"]["UserInfo"];
        };
        UserInfo: {
            /** @description 用户 ID */
            id: number;
            /** @description 登录用户名 */
            username: string;
            /** @description 展示名称 */
            displayName: string;
            /** @description 用户邮箱 */
            email: string;
            /** @description 是否具备 Django staff 标记 */
            isStaff: boolean;
            /** @description 是否为超级管理员 */
            isSuperuser: boolean;
            /** @description 用户所属 Django Group 名称列表 */
            roles: string[];
            permissions: components["schemas"]["UserPermissions"];
        };
        UserPermissions: {
            /** @description 是否可访问新版管理后台及旧版 Django 管理后台入口 */
            canAccessAdmin: boolean;
            /** @description 是否可配置功能权限 */
            canManageFeaturePermissions: boolean;
            /** @description 是否可浏览数据目录 */
            canBrowseData: boolean;
            /** @description 是否可查询数据 */
            canQueryData: boolean;
            /** @description 是否可加载矢量图层 */
            canLoadVectorLayer: boolean;
            /** @description 是否可加载栅格图层 */
            canLoadRasterLayer: boolean;
            /** @description 是否可提交自定义符号化规则 */
            canUseCustomSymbolization: boolean;
            /** @description 是否可导出数据 */
            canExportData: boolean;
            /** @description 是否可维护数据资源 */
            canMaintainData: boolean;
            /** @description 是否可管理栅格数据集 */
            canManageRasterData: boolean;
        };
        DictionaryItem: {
            /** @description 字典项 ID */
            id: number;
            /** @description 字典类型 */
            type: string;
            /** @description 字典编码 */
            code: string;
            /** @description 字典显示名称 */
            name: string;
        };
        DataResource: {
            /** @description 数据资源 ID */
            id: number;
            /** @description 数据资源名称 */
            name: string;
            /** @description 数据资源编码 */
            code: string;
            /**
             * @description 数据资源类型
             * @enum {string}
             */
            dataType: "vector" | "raster" | "gene" | "table" | "document" | "image";
            /** @description 数据分类，未分类时为 null */
            category: components["schemas"]["DictionaryItem"] | null;
            /** @description 数据来源 */
            source: string;
            /** @description 数据提供单位 */
            provider: string;
            /**
             * Format: date
             * @description 数据日期
             */
            dataDate: string | null;
            /** @description 空间范围文本 */
            spatialExtent: string;
            /** @description 坐标系统描述 */
            coordinateSystem: string;
            /** @description 文件格式 */
            fileFormat: string;
            /** @description 资源描述 */
            description: string;
            /** @description 数据质量说明 */
            qualityNote: string;
            /**
             * @description 数据资源状态
             * @enum {string}
             */
            status: "active" | "inactive";
            /** @description 是否支持矢量属性和空间查询 */
            isQueryable: boolean;
            /** @description 是否支持地图渲染 */
            isRenderable: boolean;
            /**
             * Format: date-time
             * @description 最后更新时间
             */
            updatedAt: string;
        };
        VectorLayerResource: {
            /** @description 由 GeoPackage 图层名称生成的临时资源 ID */
            id: string;
            /** @description GeoPackage 图层名称 */
            name: string;
            /** @description 由 GeoPackage 图层名称生成的临时资源编码 */
            code: string;
            /**
             * @description 数据类型，统一 GeoPackage 图层固定为 vector
             * @enum {string}
             */
            dataType: "vector";
            /**
             * @description 图层类型，统一 GeoPackage 图层固定为 vector
             * @enum {string}
             */
            layerType: "vector";
            /** @description 几何类型 */
            geometryType: string;
            /** @description WGS84 边界 [minLng, minLat, maxLng, maxLat]，无法计算时为空数组 */
            bounds: number[];
            /** @description 坐标系统描述 */
            coordinateSystem: string;
            /** @description 要素数量 */
            featureCount: number | null;
            /** @description 数据来源说明 */
            source: string;
            /** @description 是否支持查询 */
            isQueryable: boolean;
            /** @description 是否支持栅格渲染 */
            isRenderable: boolean;
            /**
             * @description 临时矢量资源状态
             * @enum {string}
             */
            status: "active";
        };
        ResourceListItem: components["schemas"]["DataResource"] | components["schemas"]["VectorLayerResource"];
        MapLayer: {
            /** @description 图层 ID */
            id: number;
            /** @description 图层名称 */
            name: string;
            /** @description 图层编码 */
            code: string;
            /**
             * @description 图层类型
             * @enum {string}
             */
            layerType: "vector" | "raster";
            /**
             * @description 几何类型
             * @enum {string}
             */
            geometryType: "point" | "line" | "polygon" | "mixed";
            /** @description 图层分类，未分类时为 null */
            category: components["schemas"]["DictionaryItem"] | null;
            /** @description 关联数据资源 ID */
            dataResourceId: number | null;
            /** @description 排序值 */
            sortOrder: number;
            /** @description 是否默认显示 */
            defaultVisible: boolean;
            /** @description 默认透明度百分比 */
            defaultOpacity: number;
            /** @description 矢量默认符号化配置 */
            symbolization: {
                [key: string]: string | number | boolean;
            };
            /** @description 图层边界 */
            bounds: number[];
            /** @description 图例说明 */
            legend: string;
            rasterRules: components["schemas"]["RasterSymbolizationRules"];
            /** @description 是否启用 */
            isActive: boolean;
            /**
             * Format: date-time
             * @description 最后更新时间
             */
            updatedAt: string;
        };
        Achievement: {
            /** @description 成果 ID */
            id: number;
            /** @description 成果标题 */
            title: string;
            /** @description 成果编码 */
            code: string;
            /** @description 成果分类，未分类时为 null */
            category: components["schemas"]["DictionaryItem"] | null;
            /** @description 成果摘要 */
            summary: string;
            /** @description 成果来源 */
            source: string;
            /** @description 关联图层 ID */
            relatedLayerId: number | null;
            /** @description 展示排序值 */
            displayOrder: number;
            /**
             * @description 成果发布状态
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /**
             * Format: date-time
             * @description 最后更新时间
             */
            updatedAt: string;
        };
        RasterDataset: {
            /** @description 栅格数据集 ID */
            id: number;
            /** @description 数据集名称 */
            name: string;
            /** @description 数据集编码 */
            code: string;
            /**
             * @description 预处理状态
             * @enum {string}
             */
            status: "pending" | "processing" | "ready" | "failed";
            /** @description 原始栅格相对路径 */
            sourcePath: string;
            /** @description 预处理 COG 相对路径 */
            processedPath: string;
            /** @description 原始文件元数据相对路径 */
            sourceMetadataPath: string;
            /** @description 预处理文件元数据相对路径 */
            processedMetadataPath: string;
            /** @description 关联数据资源 ID */
            dataResourceId: number | null;
            /** @description 关联地图图层 ID */
            mapLayerId: number | null;
            /** @description 波段数量 */
            bandCount: number;
            /** @description EPSG:3857 边界 */
            bounds3857: number[];
            /** @description WGS84 边界 */
            bounds4326: number[];
            /** @description WGS84 图像角点坐标 */
            imageCoordinates: [
                number,
                number
            ][];
            defaultRules: components["schemas"]["RasterSymbolizationRules"];
            /** @description 原始文件大小，单位字节 */
            sourceFileSize: number;
            /** @description 预处理文件大小，单位字节 */
            processedFileSize: number;
            /** @description 导入或预处理日志 */
            progressLog: string;
            /** @description 失败原因 */
            errorMessage: string;
            /**
             * Format: date-time
             * @description 导入完成时间
             */
            importedAt: string | null;
            /**
             * Format: date-time
             * @description 预处理完成时间
             */
            processedAt: string | null;
            metadata: components["schemas"]["RasterMetadata"];
        };
        RasterMetadata: {
            /** @description 栅格像素尺寸 [width, height] */
            size: number[];
            /** @description GDAL 驱动简称 */
            driver: string;
            /** @description 坐标系统 EPSG 或描述文本 */
            coordinateSystem: string | number;
            /** @description 波段元数据 */
            bands: components["schemas"]["RasterBandInfo"][];
        };
        RasterBandInfo: {
            /** @description 1-based 波段编号 */
            band: number;
            /** @description GDAL 波段类型 */
            type: string;
            /** @description 波段描述 */
            description: string;
            /** @description 颜色解释 */
            colorInterpretation: string;
            /** @description 波段最小值 */
            min: number;
            /** @description 波段最大值 */
            max: number;
            /** @description 是否为整型波段 */
            isInteger: boolean;
        };
        /** @description 栅格符号化规则对象，具体结构由后端符号化规则引擎校验 */
        RasterSymbolizationRules: {
            [key: string]: unknown;
        };
        AsyncJobResponse: {
            /** @description 异步任务 ID */
            id: string;
            /**
             * @description 任务类型
             * @enum {string}
             */
            kind: "import" | "scan" | "render" | "export";
            /**
             * @description 任务状态
             * @enum {string}
             */
            status: "queued" | "running" | "ready" | "failed";
            /** @description 任务进度百分比 */
            progressPercent: number;
            /** @description 任务进度消息 */
            messages: string[];
            /** @description 任务完成后的结果；未完成或失败时为 null */
            result: (components["schemas"]["RasterRenderResult"] | components["schemas"]["RasterDataset"] | components["schemas"]["RasterDatasetScanResult"] | components["schemas"]["ExportJobResult"]) | null;
            /** @description 失败原因 */
            error: string;
            /**
             * Format: double
             * @description 任务创建时间戳
             */
            startedAt: number;
            /**
             * Format: double
             * @description 任务结束时间戳
             */
            finishedAt: number | null;
        };
        RasterDatasetScanResult: {
            /** @description 扫描或导入得到的栅格数据集 */
            items: components["schemas"]["RasterDataset"][];
            /** @description 数据集数量 */
            count: number;
        };
        ExportJobResult: {
            /** @description 导出文件名 */
            filename: string;
            /** @description 导出文件下载路径 */
            downloadUrl: string;
        };
        DirectoryTreeResponse: {
            /** @description 数据目录列表 */
            items: components["schemas"]["Directory"][];
        };
        Directory: {
            /** @description 目录 ID */
            id: number;
            /** @description 目录名称 */
            name: string;
            /** @description 目录编码 */
            code: string;
            /** @description 父目录 ID */
            parentId: number | null;
            /** @description 目录描述 */
            description: string;
            /** @description 排序值 */
            sortOrder: number;
            /** @description 目录下的数据资源 */
            resources: components["schemas"]["DataResource"][];
        };
        ResourceListResponse: {
            /** @description 数据资源列表，可能包含统一 GeoPackage 中的临时矢量资源 */
            items: components["schemas"]["ResourceListItem"][];
        };
        ScanResponse: {
            /** @description 本次扫描发现或同步的资源 */
            items: components["schemas"]["ResourceListItem"][];
            /** @description 资源数量 */
            count: number;
        };
        ImportPreviewResponse: {
            /** @description 表格列名 */
            columns: string[];
            /** @description 前若干行预览数据，键为列名，值为文本 */
            rows: {
                [key: string]: string;
            }[];
            /** @description 总行数 */
            rowCount: number;
            /** @description 建议入库表名 */
            suggestedTableName: string;
            /** @description 建议数据名称 */
            suggestedName: string;
            detected: components["schemas"]["ImportDetectedInfo"];
            /** @description 导入限制提示 */
            limitations: string[];
        };
        ImportDetectedInfo: {
            /** @description 是否自动识别为地理表 */
            isGeographic: boolean;
            /** @description 自动识别的经度列 */
            longitudeColumn: string | null;
            /** @description 自动识别的纬度列 */
            latitudeColumn: string | null;
            /** @description 坐标统计，预览阶段为 null */
            coordinateStats: components["schemas"]["CoordinateStats"] | null;
            /** @description 坐标校验问题，预览阶段为空数组 */
            validationIssues: components["schemas"]["ValidationIssue"][];
        };
        ImportValidateResponse: {
            /** @description 坐标统计；非地理导入时为 null */
            coordinateStats: components["schemas"]["CoordinateStats"] | null;
            /** @description 坐标校验问题 */
            validationIssues: components["schemas"]["ValidationIssue"][];
        };
        CoordinateStats: {
            /** @description 总行数 */
            totalRows: number;
            /** @description 坐标有效行数 */
            validRows: number;
            /** @description 缺少或无效坐标行数 */
            missingRows: number;
            /** @description 坐标文本小数位引入的位置误差范围，单位米 */
            quantizationErrorMeters: {
                /** @description 最小估算误差 */
                min: number | null;
                /** @description 最大估算误差 */
                max: number | null;
            };
        };
        ImportCommitResponse: components["schemas"]["GeographicImportCommitResponse"] | components["schemas"]["TableImportCommitResponse"];
        GeographicImportCommitResponse: {
            /**
             * @description 地理表导入模式
             * @enum {string}
             */
            mode: "geographic";
            /** @description 创建或更新的数据资源 ID */
            resourceId: number;
            /** @description 创建或更新的数据资源名称 */
            resourceName: string;
            /** @description 写入 GeoPackage 的图层名 */
            layerName: string;
            /** @description 写入 GeoPackage 的图层名，与 layerName 相同 */
            tableName: string;
            /** @description 成功导入行数 */
            importedRows: number;
            /** @description 跳过行数 */
            skippedRows: number;
            /** @description 导入数据边界 [minLng, minLat, maxLng, maxLat]，无有效坐标时为空数组 */
            bounds: number[];
            coordinateStats: components["schemas"]["CoordinateStats"];
            /** @description 导入时发现的坐标校验问题 */
            validationIssues: components["schemas"]["ValidationIssue"][];
        };
        TableImportCommitResponse: {
            /**
             * @description 非地理表导入模式
             * @enum {string}
             */
            mode: "table";
            /** @description 创建或更新的数据资源 ID */
            resourceId: number;
            /** @description 创建或更新的数据资源名称 */
            resourceName: string;
            /** @description 非地理表不创建地图图层，固定为 null */
            layerId: number | null;
            /** @description SQLite 表名 */
            tableName: string;
            /** @description 成功导入行数 */
            importedRows: number;
            /** @description 跳过行数 */
            skippedRows: number;
            /** @description 非地理导入固定为 null */
            coordinateStats: components["schemas"]["CoordinateStats"] | null;
            /** @description 非地理导入固定为空数组 */
            validationIssues: components["schemas"]["ValidationIssue"][];
        };
        ImportErrorResponse: {
            /** @description 导入失败说明 */
            detail: string;
            /** @description 导入校验问题 */
            issues?: components["schemas"]["ValidationIssue"][];
        };
        ValidationIssue: {
            /** @description 问题代码 */
            code: string;
            /** @description 问题说明 */
            message: string;
            /** @description 是否阻断导入 */
            blocking: boolean;
            /** @description 受影响行数 */
            count?: number;
            /** @description 坐标不确定性最小误差，单位米 */
            minMeters?: number;
            /** @description 坐标不确定性最大误差，单位米 */
            maxMeters?: number;
            /** @description 坐标不确定性误差倍率 */
            ratio?: number;
        };
        ResourceProfileResponse: {
            resource: components["schemas"]["ResourceListItem"];
            /** @description 属性字段信息 */
            fields: components["schemas"]["FieldInfo"][];
            /** @description 矢量要素数量；栅格和非空间资源为 null */
            featureCount: number | null;
            /** @description 几何类型 */
            geometryType: string;
            /** @description WGS84 边界 [minLng, minLat, maxLng, maxLat]，无法计算时为空数组 */
            bounds: number[];
            /** @description 栅格资源详情；非栅格资源可能省略或为 null */
            raster?: components["schemas"]["RasterDataset"] | null;
        };
        FieldInfo: {
            /** @description 字段名 */
            name: string;
            /** @description 字段数据类型 */
            type: string;
            /** @description 是否存在空值 */
            nullable: boolean;
            /** @description 非空样例值 */
            sampleValues: (string | number | boolean | null)[];
            /** @description 字段描述 */
            description: string;
        };
        QueryRequest: {
            /** @description 属性过滤条件 */
            attributeFilters: components["schemas"]["AttributeFilter"][];
            /** @description 空间过滤条件；不启用空间过滤时为 null */
            spatialFilter: components["schemas"]["SpatialFilter"] | null;
            /**
             * @description 返回结果上限
             * @default 30000
             */
            limit: number;
        };
        AttributeFilter: {
            /** @description 字段名 */
            field: string;
            /**
             * @description 过滤操作符
             * @enum {string}
             */
            operator: "contains" | "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "between";
            /** @description 过滤值 */
            value: string;
            /** @description between 操作符时使用的结束值 */
            valueTo?: string;
        };
        SpatialFilter: {
            /**
             * @description 空间过滤绘制模式
             * @enum {string}
             */
            mode: "rectangle" | "circle" | "ellipse" | "polygon";
            geometry: components["schemas"]["GeoJSONGeometry"];
        };
        QueryResponse: {
            /** @description 查询资源 ID；临时 GeoPackage 图层查询时为字符串 ID */
            resourceId: number | string;
            /** @description 查询资源名称 */
            resourceName: string;
            /** @description 过滤后的总数 */
            totalCount: number;
            /** @description 本次返回数量 */
            returnedCount: number;
            /** @description 返回上限 */
            limit: number;
            /** @description 查询结果字段 */
            fields: components["schemas"]["FieldInfo"][];
            geojson: components["schemas"]["GeoJSONFeatureCollection"];
            /** @description 地理坐标校验警告 */
            warnings: components["schemas"]["ValidationWarning"][];
        };
        ExportRequest: {
            /**
             * @description 目标 EPSG，reproject 为 true 时使用
             * @default 4326
             */
            epsg?: number | null;
            /**
             * @description 是否重投影导出
             * @default true
             */
            reproject: boolean;
            /**
             * @description 是否按空间范围裁切
             * @default false
             */
            clip: boolean;
            /** @description 裁切 GeoJSON 几何 */
            clipGeometry?: components["schemas"]["GeoJSONGeometry"] | null;
            /** @description 待导出图层 */
            items: components["schemas"]["ExportItem"][];
        };
        ExportItem: {
            /**
             * @description 图层类型
             * @enum {string}
             */
            layerType: "vector" | "raster";
            /** @description 导出图层名称 */
            name: string;
            /** @description 数据资源 ID；临时 GeoPackage 查询结果没有业务资源 ID，可省略或传 null */
            resourceId?: number | null;
            /** @description 前端临时矢量查询结果 */
            geojson?: components["schemas"]["GeoJSONFeatureCollection"] | null;
            /** @description 栅格数据集 ID */
            datasetId?: number | null;
            /** @description 源坐标系统 */
            sourceCrs?: (string | number) | null;
        };
        LayerListResponse: {
            /** @description 可加载图层列表 */
            items: (components["schemas"]["VectorLayerResource"] | components["schemas"]["MapLayer"])[];
        };
        AchievementListResponse: {
            /** @description 已发布成果列表 */
            items: components["schemas"]["Achievement"][];
        };
        SearchResponse: {
            /** @description 匹配的数据资源 */
            resources: components["schemas"]["ResourceListItem"][];
            /** @description 匹配的研究成果 */
            achievements: components["schemas"]["Achievement"][];
        };
        RasterDatasetListResponse: {
            /** @description 栅格数据集列表 */
            items: components["schemas"]["RasterDataset"][];
        };
        RasterImportRequest: {
            /** @description 源文件相对路径（相对于科研数据根目录） */
            sourcePath: string;
            /** @description 数据集名称，默认取文件名 */
            name?: string;
            /**
             * @description 是否异步执行
             * @default true
             */
            async?: boolean;
        };
        RasterRenderRequest: {
            /** @description 栅格图层 ID */
            layerId: number;
            /**
             * @description 符号化规则模式
             * @default default
             * @enum {string}
             */
            rulesMode?: "default" | "custom";
            /** @description 自定义符号化规则 */
            rules?: components["schemas"]["RasterSymbolizationRules"] | null;
        };
        RasterRenderAsyncRequest: {
            /** @description 栅格图层 ID */
            layerId?: number | null;
            /** @description 栅格数据集 ID */
            datasetId?: number | null;
            /**
             * @description 符号化规则模式
             * @default default
             * @enum {string}
             */
            rulesMode?: "default" | "custom";
            /** @description 自定义符号化规则 */
            rules?: components["schemas"]["RasterSymbolizationRules"] | null;
        };
        RasterRenderResult: {
            /**
             * @description 栅格交付方式
             * @enum {string}
             */
            delivery: "xyz";
            /** @description 栅格数据集 ID */
            datasetId: number;
            /** @description 关联图层 ID */
            layerId: number | null;
            /** @description 符号化样式哈希 */
            styleHash: string;
            /** @description XYZ 瓦片 URL 模板 */
            tileUrl: string;
            /**
             * @description 渲染结果状态
             * @enum {string}
             */
            status: "ready";
            /** @description EPSG:3857 边界 */
            bounds3857: number[];
            /** @description WGS84 边界 */
            bounds4326: number[];
            /** @description WGS84 图像角点坐标 */
            imageCoordinates: [
                number,
                number
            ][];
            rules: components["schemas"]["RasterSymbolizationRules"];
        };
        UniqueValuesRequest: {
            /** @description 栅格数据集 ID */
            datasetId: number;
            /**
             * @description 1-based 波段编号
             * @default 1
             */
            band?: number;
        };
        UniqueValuesResponse: {
            /** @description 1-based 波段编号 */
            band: number;
            /** @description 唯一值分类项 */
            items: {
                /** @description 栅格像元值 */
                value: number;
                /** @description 分类颜色 */
                color: string;
                /** @description 分类标签 */
                label: string;
            }[];
        };
        GeoJSONGeometry: {
            /**
             * @description GeoJSON 几何类型
             * @enum {string}
             */
            type: "Point" | "LineString" | "Polygon" | "MultiPoint" | "MultiLineString" | "MultiPolygon";
            /** @description GeoJSON 坐标数组 */
            coordinates: unknown;
        };
        /** @description 矢量图层要素响应，包含 GeoJSON FeatureCollection 和校验警告 */
        LayerFeaturesResponse: components["schemas"]["GeoJSONFeatureCollection"] & {
            /** @description 地理坐标校验警告 */
            warnings: components["schemas"]["ValidationWarning"][];
        };
        ValidationWarning: {
            /** @description 警告代码，如 missing_geometry、invalid_longitude、coordinate_uncertainty */
            code: string;
            /** @description 受影响的记录数 */
            count?: number;
            /** @description 警告描述 */
            message: string;
            /** @description 坐标不确定性最小误差，单位米 */
            minMeters?: number;
            /** @description 坐标不确定性最大误差，单位米 */
            maxMeters?: number;
            /** @description 坐标不确定性误差倍率 */
            ratio?: number;
        };
        GeoJSONFeatureCollection: {
            /**
             * @description GeoJSON FeatureCollection 类型
             * @enum {string}
             */
            type: "FeatureCollection";
            /** @description GeoJSON 要素列表 */
            features: components["schemas"]["GeoJSONFeature"][];
        };
        GeoJSONFeature: {
            /** @description GeoJSON 要素 ID */
            id?: string | number;
            /**
             * @description GeoJSON Feature 类型
             * @enum {string}
             */
            type: "Feature";
            geometry: components["schemas"]["GeoJSONGeometry"];
            /** @description GeoJSON 属性对象 */
            properties: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description 请求错误 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "请求参数错误"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "认证凭据未提供"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 权限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "当前用户组无权限"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "detail": "未找到请求的资源"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 资源 ID */
        ResourceId: number;
        /** @description 异步任务 ID */
        JobId: string;
        /** @description 统一 GeoPackage 中的矢量图层名称 */
        LayerName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getCsrfCookie: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已认证用户信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfoResponse"];
                };
            };
            /** @description 未认证 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        authenticated?: boolean;
                    };
                };
            };
        };
    };
    getDirectories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryTreeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getResources: {
        parameters: {
            query?: {
                /** @description 按名称模糊搜索 */
                q?: string;
                /** @description 数据类型筛选 */
                dataType?: "vector" | "raster" | "gene" | "table" | "document" | "image";
                /** @description 分类代码精确匹配 */
                category?: string;
                /** @description 数据来源模糊匹配 */
                source?: string;
                /** @description 提供者模糊匹配 */
                provider?: string;
                /** @description 数据日期起始 */
                dateFrom?: string;
                /** @description 数据日期截止 */
                dateTo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    scanCatalogSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 扫描完成 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importPreview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description .csv / .xls / .xlsx 文件
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description 预检成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importValidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description 与预检一致的文件
                     */
                    file: string;
                    /** @description JSON 字符串，包含 importMode、longitudeColumn、latitudeColumn */
                    payload: string;
                };
            };
        };
        responses: {
            /** @description 校验成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportValidateResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importCommit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description JSON 字符串，包含导入配置 */
                    payload: string;
                };
            };
        };
        responses: {
            /** @description 导入成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCommitResponse"];
                };
            };
            /** @description 校验失败 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getResourceProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceProfileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    queryResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 资源 ID */
                id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    exportLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description 导出成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    exportLayersAsync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description 任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    downloadExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 异步任务 ID */
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下载成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description 任务未完成 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    getLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getLayerFeatures: {
        parameters: {
            query?: {
                /** @description 返回要素上限 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description 统一 GeoPackage 中的矢量图层名称 */
                layer_name: components["parameters"]["LayerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerFeaturesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getLayerProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 统一 GeoPackage 中的矢量图层名称 */
                layer_name: components["parameters"]["LayerName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceProfileResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    queryLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 统一 GeoPackage 中的矢量图层名称 */
                layer_name: components["parameters"]["LayerName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description 查询成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getAchievements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    search: {
        parameters: {
            query?: {
                /** @description 搜索关键词，为空时返回空结果 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 搜索成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getRasterDatasets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RasterDatasetListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    importRaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RasterImportRequest"];
            };
        };
        responses: {
            /** @description 同步导入成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RasterDataset"];
                };
            };
            /** @description 异步任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    scanRasterSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    renderRaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RasterRenderRequest"];
            };
        };
        responses: {
            /** @description 渲染成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RasterRenderResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    renderRasterAsync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RasterRenderAsyncRequest"];
            };
        };
        responses: {
            /** @description 任务已提交 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getUniqueValues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniqueValuesRequest"];
            };
        };
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniqueValuesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 异步任务 ID */
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsyncJobResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 栅格数据集 ID */
                dataset_id: number;
                /** @description 样式哈希 */
                style_hash: string;
                /** @description 缩放级别 */
                z: number;
                /** @description 瓦片列号 */
                x: number;
                /** @description 瓦片行号 */
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG 瓦片 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
