# Generated by Django 6.0.6 on 2026-06-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_dataresourcegroup_dataresource_inventory_group"),
        ("raster", "0002_normalize_uploaded_raster_display_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "population_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="种群编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="种群名称"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "geometry_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="population_geometries",
                        to="catalog.dataresource",
                        verbose_name="种群空间资源",
                    ),
                ),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="population_units",
                        to="catalog.maplayer",
                        verbose_name="种群图层",
                    ),
                ),
            ],
            options={
                "verbose_name": "种群单元",
                "verbose_name_plural": "种群单元",
                "ordering": ("population_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="RemoteSensingProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.SlugField(
                        blank=True,
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="产品编码",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="产品名称")),
                (
                    "product_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="产品类型"
                    ),
                ),
                (
                    "sensor",
                    models.CharField(blank=True, max_length=120, verbose_name="传感器"),
                ),
                (
                    "acquired_on",
                    models.DateField(blank=True, null=True, verbose_name="获取日期"),
                ),
                (
                    "period_start",
                    models.DateField(blank=True, null=True, verbose_name="周期开始"),
                ),
                (
                    "period_end",
                    models.DateField(blank=True, null=True, verbose_name="周期结束"),
                ),
                (
                    "resolution",
                    models.CharField(blank=True, max_length=80, verbose_name="分辨率"),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="指数名称"
                    ),
                ),
                (
                    "bounds_4326",
                    models.JSONField(
                        blank=True, default=list, verbose_name="经纬度范围"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="产品元数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "data_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_sensing_products",
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_sensing_products",
                        to="catalog.maplayer",
                        verbose_name="地图图层",
                    ),
                ),
                (
                    "raster_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remote_sensing_products",
                        to="raster.rasterdataset",
                        verbose_name="栅格数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "遥感产品",
                "verbose_name_plural": "遥感产品",
                "ordering": ("-acquired_on", "name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="地点编码",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="地点名称")),
                (
                    "admin_region",
                    models.CharField(blank=True, max_length=200, verbose_name="行政区"),
                ),
                (
                    "raw_location",
                    models.TextField(blank=True, verbose_name="原始地点描述"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔"),
                ),
                (
                    "coordinate_system",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="坐标系统"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecology_sites",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "采集地点/样地",
                "verbose_name_plural": "采集地点/样地",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="SamplePlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plot_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="样方编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="样方名称"
                    ),
                ),
                (
                    "plot_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="样方类型"
                    ),
                ),
                (
                    "raw_longitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始经度"
                    ),
                ),
                (
                    "raw_latitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始纬度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔"),
                ),
                (
                    "area_square_meters",
                    models.FloatField(
                        blank=True, null=True, verbose_name="样方面积平方米"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_plots",
                        to="catalog.maplayer",
                        verbose_name="样方图层",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_plots",
                        to="ecology.populationunit",
                        verbose_name="种群",
                    ),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_plots",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_plots",
                        to="ecology.site",
                        verbose_name="地点",
                    ),
                ),
            ],
            options={
                "verbose_name": "样方/样点",
                "verbose_name_plural": "样方/样点",
                "ordering": ("plot_code", "id"),
            },
        ),
        migrations.AddField(
            model_name="populationunit",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="populations",
                to="ecology.site",
                verbose_name="地点",
            ),
        ),
        migrations.CreateModel(
            name="IndividualOrganism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "individual_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="个体编码",
                    ),
                ),
                (
                    "sex",
                    models.CharField(blank=True, max_length=40, verbose_name="性别"),
                ),
                (
                    "growth_stage",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="生长阶段"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="健康状态"
                    ),
                ),
                (
                    "raw_longitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始经度"
                    ),
                ),
                (
                    "raw_latitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始纬度"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "altitude",
                    models.FloatField(blank=True, null=True, verbose_name="海拔"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="ecology.populationunit",
                        verbose_name="种群",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="ecology.site",
                        verbose_name="地点",
                    ),
                ),
            ],
            options={
                "verbose_name": "植物个体",
                "verbose_name_plural": "植物个体",
                "ordering": ("individual_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="StudyArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_code",
                    models.SlugField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="区域编码",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="区域名称")),
                (
                    "area_type",
                    models.CharField(
                        choices=[
                            ("basin", "流域"),
                            ("region", "区域"),
                            ("protected_area", "保护地"),
                            ("administrative", "行政区"),
                            ("other", "其他"),
                        ],
                        default="region",
                        max_length=32,
                        verbose_name="区域类型",
                    ),
                ),
                (
                    "admin_region",
                    models.CharField(blank=True, max_length=160, verbose_name="行政区"),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "boundary_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_areas",
                        to="catalog.maplayer",
                        verbose_name="边界图层",
                    ),
                ),
                (
                    "boundary_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_area_boundaries",
                        to="catalog.dataresource",
                        verbose_name="边界数据资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究区域",
                "verbose_name_plural": "研究区域",
                "ordering": ("name", "id"),
            },
        ),
        migrations.AddField(
            model_name="site",
            name="study_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="ecology.studyarea",
                verbose_name="研究区域",
            ),
        ),
        migrations.AddField(
            model_name="populationunit",
            name="study_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="populations",
                to="ecology.studyarea",
                verbose_name="研究区域",
            ),
        ),
        migrations.CreateModel(
            name="SurveyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "survey_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="调查编码",
                    ),
                ),
                ("name", models.CharField(max_length=180, verbose_name="调查名称")),
                (
                    "survey_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="调查类型"
                    ),
                ),
                (
                    "started_on",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "ended_on",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "principal",
                    models.CharField(blank=True, max_length=120, verbose_name="负责人"),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="调查队伍"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_events",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "study_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_events",
                        to="ecology.studyarea",
                        verbose_name="研究区域",
                    ),
                ),
            ],
            options={
                "verbose_name": "野外调查事件",
                "verbose_name_plural": "野外调查事件",
                "ordering": ("-started_on", "name", "id"),
            },
        ),
        migrations.AddField(
            model_name="sampleplot",
            name="survey_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sample_plots",
                to="ecology.surveyevent",
                verbose_name="调查事件",
            ),
        ),
        migrations.AddField(
            model_name="populationunit",
            name="survey_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="populations",
                to="ecology.surveyevent",
                verbose_name="调查事件",
            ),
        ),
        migrations.CreateModel(
            name="CommunitySurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "community_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="群落调查编码",
                    ),
                ),
                (
                    "vegetation_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="植被类型"
                    ),
                ),
                (
                    "layer_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="群落层片"
                    ),
                ),
                (
                    "total_coverage_percent",
                    models.FloatField(
                        blank=True, null=True, verbose_name="总盖度百分比"
                    ),
                ),
                (
                    "species_count",
                    models.PositiveIntegerField(default=0, verbose_name="物种数"),
                ),
                (
                    "diversity_index",
                    models.FloatField(blank=True, null=True, verbose_name="多样性指数"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_surveys",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_surveys",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "survey_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_surveys",
                        to="ecology.surveyevent",
                        verbose_name="调查事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "群落调查",
                "verbose_name_plural": "群落调查",
                "ordering": ("community_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="SurveyRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "route_code",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="路线编码",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="路线名称"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "line_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_routes",
                        to="catalog.dataresource",
                        verbose_name="路线空间资源",
                    ),
                ),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_routes",
                        to="catalog.maplayer",
                        verbose_name="路线图层",
                    ),
                ),
                (
                    "survey_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="survey_routes",
                        to="ecology.surveyevent",
                        verbose_name="调查事件",
                    ),
                ),
            ],
            options={
                "verbose_name": "调查路线",
                "verbose_name_plural": "调查路线",
                "ordering": ("route_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        blank=True,
                        max_length=80,
                        null=True,
                        unique=True,
                        verbose_name="物种编码",
                    ),
                ),
                (
                    "name_cn",
                    models.CharField(blank=True, max_length=120, verbose_name="中文名"),
                ),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=160, verbose_name="科学名"),
                ),
                (
                    "family",
                    models.CharField(blank=True, max_length=120, verbose_name="科"),
                ),
                (
                    "genus",
                    models.CharField(blank=True, max_length=120, verbose_name="属"),
                ),
                (
                    "protection_level",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="保护等级"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "物种",
                "verbose_name_plural": "物种",
                "ordering": ("name_cn", "scientific_name", "id"),
                "indexes": [
                    models.Index(
                        fields=["name_cn"], name="ecology_tax_name_cn_e2363e_idx"
                    ),
                    models.Index(
                        fields=["scientific_name"],
                        name="ecology_tax_scienti_3ab149_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SpecimenRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specimen_code",
                    models.SlugField(
                        blank=True,
                        max_length=120,
                        null=True,
                        unique=True,
                        verbose_name="标本编码",
                    ),
                ),
                (
                    "sample_code",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="样品编号"
                    ),
                ),
                (
                    "material_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="材料类型"
                    ),
                ),
                (
                    "collector",
                    models.CharField(blank=True, max_length=120, verbose_name="采集人"),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="采集时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens",
                        to="ecology.individualorganism",
                        verbose_name="个体",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens",
                        to="ecology.site",
                        verbose_name="地点",
                    ),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "survey_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens",
                        to="ecology.surveyevent",
                        verbose_name="调查事件",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="specimens",
                        to="ecology.taxon",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "标本/采样记录",
                "verbose_name_plural": "标本/采样记录",
                "ordering": ("specimen_code", "id"),
            },
        ),
        migrations.CreateModel(
            name="SpeciesComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_taxon_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="原始物种名"
                    ),
                ),
                (
                    "abundance",
                    models.FloatField(blank=True, null=True, verbose_name="多度"),
                ),
                (
                    "coverage_percent",
                    models.FloatField(blank=True, null=True, verbose_name="盖度百分比"),
                ),
                (
                    "frequency",
                    models.FloatField(blank=True, null=True, verbose_name="频度"),
                ),
                (
                    "importance_value",
                    models.FloatField(blank=True, null=True, verbose_name="重要值"),
                ),
                (
                    "life_form",
                    models.CharField(blank=True, max_length=80, verbose_name="生活型"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "community_survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species_compositions",
                        to="ecology.communitysurvey",
                        verbose_name="群落调查",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="community_compositions",
                        to="ecology.taxon",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "群落物种组成",
                "verbose_name_plural": "群落物种组成",
                "ordering": ("community_survey_id", "id"),
            },
        ),
        migrations.AddField(
            model_name="populationunit",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="populations",
                to="ecology.taxon",
                verbose_name="物种",
            ),
        ),
        migrations.AddField(
            model_name="individualorganism",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="individuals",
                to="ecology.taxon",
                verbose_name="物种",
            ),
        ),
        migrations.CreateModel(
            name="FieldObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="观测类型"
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="观测时间"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                ("description", models.TextField(blank=True, verbose_name="观测描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="ecology.individualorganism",
                        verbose_name="个体",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="ecology.site",
                        verbose_name="地点",
                    ),
                ),
                (
                    "survey_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="ecology.surveyevent",
                        verbose_name="调查事件",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="field_observations",
                        to="ecology.taxon",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "野外观测记录",
                "verbose_name_plural": "野外观测记录",
                "ordering": ("-observed_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="TaxonAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=160, verbose_name="别名")),
                (
                    "source",
                    models.CharField(blank=True, max_length=160, verbose_name="来源"),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="ecology.taxon",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "物种别名",
                "verbose_name_plural": "物种别名",
            },
        ),
        migrations.CreateModel(
            name="TraitObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="观测时间"
                    ),
                ),
                (
                    "trait_code",
                    models.SlugField(max_length=100, verbose_name="性状编码"),
                ),
                (
                    "trait_name",
                    models.CharField(max_length=160, verbose_name="性状名称"),
                ),
                (
                    "value_text",
                    models.CharField(blank=True, max_length=255, verbose_name="文本值"),
                ),
                (
                    "value_numeric",
                    models.FloatField(blank=True, null=True, verbose_name="数值"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trait_observations",
                        to="ecology.individualorganism",
                        verbose_name="个体",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trait_observations",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "source_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trait_observations",
                        to="catalog.dataresource",
                        verbose_name="来源数据资源",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trait_observations",
                        to="ecology.taxon",
                        verbose_name="物种",
                    ),
                ),
            ],
            options={
                "verbose_name": "功能性状观测",
                "verbose_name_plural": "功能性状观测",
                "ordering": ("-observed_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CommunityMetricValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_code",
                    models.SlugField(max_length=100, verbose_name="指标编码"),
                ),
                (
                    "metric_name",
                    models.CharField(max_length=160, verbose_name="指标名称"),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="指标值"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="计算方法"
                    ),
                ),
                (
                    "community_survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_values",
                        to="ecology.communitysurvey",
                        verbose_name="群落调查",
                    ),
                ),
            ],
            options={
                "verbose_name": "群落指标值",
                "verbose_name_plural": "群落指标值",
                "ordering": ("community_survey_id", "metric_code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("community_survey", "metric_code"),
                        name="uniq_community_metric",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RasterSampleValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "sampled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="采样时间"
                    ),
                ),
                (
                    "band_name",
                    models.CharField(blank=True, max_length=80, verbose_name="波段"),
                ),
                (
                    "metric_code",
                    models.SlugField(
                        blank=True, max_length=100, verbose_name="指标编码"
                    ),
                ),
                (
                    "value",
                    models.FloatField(blank=True, null=True, verbose_name="采样值"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                (
                    "individual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_sample_values",
                        to="ecology.individualorganism",
                        verbose_name="个体",
                    ),
                ),
                (
                    "population",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_sample_values",
                        to="ecology.populationunit",
                        verbose_name="种群",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_values",
                        to="ecology.remotesensingproduct",
                        verbose_name="遥感产品",
                    ),
                ),
                (
                    "sample_plot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_sample_values",
                        to="ecology.sampleplot",
                        verbose_name="样方",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_sample_values",
                        to="ecology.site",
                        verbose_name="地点",
                    ),
                ),
            ],
            options={
                "verbose_name": "遥感采样值",
                "verbose_name_plural": "遥感采样值",
                "ordering": ("product_id", "id"),
                "indexes": [
                    models.Index(
                        fields=["longitude", "latitude"],
                        name="ecology_ras_longitu_45e50b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["longitude", "latitude"], name="ecology_sit_longitu_cbec87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["admin_region"], name="ecology_sit_admin_r_c6d227_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sampleplot",
            index=models.Index(
                fields=["longitude", "latitude"], name="ecology_sam_longitu_97fa51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individualorganism",
            index=models.Index(
                fields=["longitude", "latitude"], name="ecology_ind_longitu_1439a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldobservation",
            index=models.Index(
                fields=["longitude", "latitude"], name="ecology_fie_longitu_0cf861_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxonalias",
            constraint=models.UniqueConstraint(
                fields=("taxon", "alias"), name="uniq_taxon_alias"
            ),
        ),
        migrations.AddIndex(
            model_name="traitobservation",
            index=models.Index(
                fields=["trait_code"], name="ecology_tra_trait_c_9c4fc7_idx"
            ),
        ),
    ]
