# Generated by Django 6.0.6 on 2026-06-20 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=64, verbose_name="模块")),
                ("action", models.CharField(max_length=64, verbose_name="操作")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("warning", "告警"),
                            ("failed", "失败"),
                        ],
                        max_length=16,
                        verbose_name="结果",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="目标后台 ID"
                    ),
                ),
                (
                    "target_code",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="目标编码"
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="目标名称"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="说明")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["module", "action"],
                        name="audit_opera_module_596fad_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_opera_target__f440b1_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_opera_created_837649_idx"
                    ),
                ],
            },
        ),
    ]
