# Generated by Django 6.0.5 on 2026-05-26 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RasterCacheRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(max_length=64, unique=True, verbose_name="缓存标识"),
                ),
                (
                    "raster_relative_path",
                    models.CharField(max_length=255, verbose_name="栅格相对路径"),
                ),
                (
                    "png_relative_path",
                    models.CharField(max_length=255, verbose_name="PNG 缓存相对路径"),
                ),
                (
                    "rules",
                    models.JSONField(blank=True, default=dict, verbose_name="符号化规则"),
                ),
                ("output_width", models.PositiveIntegerField(verbose_name="输出宽度")),
                ("output_height", models.PositiveIntegerField(verbose_name="输出高度")),
                (
                    "file_size",
                    models.PositiveBigIntegerField(default=0, verbose_name="文件大小"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "可用"), ("failed", "失败")],
                        default="ready",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="生成时间"),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, verbose_name="最近访问时间"),
                ),
                (
                    "data_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.maplayer",
                        verbose_name="图层",
                    ),
                ),
            ],
            options={
                "verbose_name": "栅格 PNG 缓存",
                "verbose_name_plural": "栅格 PNG 缓存",
                "ordering": ("-last_accessed_at",),
                "permissions": [("manage_raster_cache", "可管理栅格 PNG 缓存")],
            },
        ),
    ]
