# Generated by Django 6.0.6 on 2026-06-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RasterDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="数据名称")),
                (
                    "code",
                    models.SlugField(
                        max_length=96, unique=True, verbose_name="数据编号"
                    ),
                ),
                (
                    "source_relative_path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="源文件相对路径"
                    ),
                ),
                (
                    "processed_relative_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="预处理文件相对路径"
                    ),
                ),
                (
                    "source_metadata_relative_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="源文件元数据路径"
                    ),
                ),
                (
                    "processed_metadata_relative_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="预处理文件元数据路径"
                    ),
                ),
                (
                    "source_gdalinfo",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="源文件 GDAL 元数据"
                    ),
                ),
                (
                    "processed_gdalinfo",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="预处理文件 GDAL 元数据"
                    ),
                ),
                (
                    "default_rules",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="默认符号化规则"
                    ),
                ),
                (
                    "bounds_3857",
                    models.JSONField(
                        blank=True, default=list, verbose_name="EPSG:3857 范围"
                    ),
                ),
                (
                    "bounds_4326",
                    models.JSONField(
                        blank=True, default=list, verbose_name="经纬度范围"
                    ),
                ),
                (
                    "image_coordinates",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Mapbox 图片角点"
                    ),
                ),
                (
                    "band_count",
                    models.PositiveIntegerField(default=0, verbose_name="波段数"),
                ),
                (
                    "source_file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="源文件大小"
                    ),
                ),
                (
                    "processed_file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="预处理文件大小"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待处理"),
                            ("processing", "处理中"),
                            ("ready", "可用"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("progress_log", models.TextField(blank=True, verbose_name="处理日志")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "imported_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导入时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预处理完成时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "data_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_datasets",
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_datasets",
                        to="catalog.maplayer",
                        verbose_name="地图图层",
                    ),
                ),
            ],
            options={
                "verbose_name": "栅格数据集",
                "verbose_name_plural": "栅格数据集",
                "ordering": ("-imported_at",),
                "permissions": [("manage_raster_dataset", "可管理栅格数据集")],
            },
        ),
    ]
