# Generated by Codex on 2026-06-22

import re
from pathlib import PurePosixPath

from django.db import migrations


UPLOADED_SOURCE_NAME_PATTERN = re.compile(r"^[0-9a-fA-F]{32}-(?P<name>.+)$")


def normalize_uploaded_raster_names(apps, schema_editor):
    RasterDataset = apps.get_model("raster", "RasterDataset")

    for dataset in RasterDataset.objects.filter(
        source_relative_path__startswith="uploaded/"
    ).select_related("data_resource", "map_layer"):
        old_name = dataset.name
        source_stem = PurePosixPath(dataset.source_relative_path).stem
        match = UPLOADED_SOURCE_NAME_PATTERN.fullmatch(source_stem)
        if not match or old_name != source_stem:
            continue

        display_name = match.group("name")
        dataset.name = display_name
        dataset.save(update_fields=["name", "updated_at"])

        if dataset.data_resource_id and dataset.data_resource.name == old_name:
            dataset.data_resource.name = display_name
            dataset.data_resource.save(update_fields=["name", "updated_at"])

        if dataset.map_layer_id and dataset.map_layer.name == old_name:
            dataset.map_layer.name = display_name
            dataset.map_layer.save(update_fields=["name"])


class Migration(migrations.Migration):
    dependencies = [
        ("raster", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            normalize_uploaded_raster_names, migrations.RunPython.noop
        ),
    ]
