# Generated by Django 6.0.6 on 2026-07-13 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raster", "0002_normalize_uploaded_raster_display_names"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rasterdataset",
            name="raster_kind",
            field=models.CharField(
                choices=[
                    ("imagery", "多波段影像"),
                    ("continuous", "连续型栅格"),
                    ("categorical", "分类栅格"),
                ],
                default="imagery",
                max_length=20,
                verbose_name="栅格数据语义",
            ),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="resampling",
            field=models.CharField(
                default="bilinear", max_length=20, verbose_name="预处理重采样方式"
            ),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="source_checksum_sha256",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="源主文件 SHA256"
            ),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="source_file_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="源主文件原始名称"
            ),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="source_format",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="源栅格格式"
            ),
        ),
        migrations.AddField(
            model_name="rasterdataset",
            name="source_manifest",
            field=models.JSONField(
                blank=True, default=list, verbose_name="源数据包文件清单"
            ),
        ),
        migrations.CreateModel(
            name="RasterProcessingJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=32, primary_key=True, serialize=False
                    ),
                ),
                ("kind", models.CharField(max_length=24, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "等待处理"),
                            ("running", "处理中"),
                            ("ready", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="queued",
                        max_length=16,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        default="queued", max_length=32, verbose_name="处理阶段"
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(default=0, verbose_name="进度"),
                ),
                (
                    "messages",
                    models.JSONField(blank=True, default=list, verbose_name="进度消息"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, null=True, verbose_name="任务结果"),
                ),
                ("error", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "artifact_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="任务产物路径"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_processing_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "栅格处理任务",
                "verbose_name_plural": "栅格处理任务",
                "ordering": ("-started_at",),
            },
        ),
        migrations.CreateModel(
            name="RasterBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("band_index", models.PositiveIntegerField(verbose_name="波段序号")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="波段名称"
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="数据类型"
                    ),
                ),
                (
                    "color_interpretation",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="颜色解释"
                    ),
                ),
                (
                    "nodata",
                    models.FloatField(blank=True, null=True, verbose_name="NoData 值"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                (
                    "minimum",
                    models.FloatField(blank=True, null=True, verbose_name="最小值"),
                ),
                (
                    "maximum",
                    models.FloatField(blank=True, null=True, verbose_name="最大值"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="波段元数据"
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="band_records",
                        to="raster.rasterdataset",
                        verbose_name="栅格数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "栅格波段",
                "verbose_name_plural": "栅格波段",
                "ordering": ("dataset_id", "band_index"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "band_index"), name="uniq_raster_band_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RasterStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "style_hash",
                    models.CharField(max_length=24, verbose_name="样式哈希"),
                ),
                ("rules", models.JSONField(default=dict, verbose_name="符号化规则")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后使用时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raster_styles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="render_styles",
                        to="raster.rasterdataset",
                        verbose_name="栅格数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "栅格渲染样式",
                "verbose_name_plural": "栅格渲染样式",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "style_hash"),
                        name="uniq_raster_dataset_style",
                    )
                ],
            },
        ),
    ]
