# Generated by Codex on 2026-05-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("raster", "0002_rasterdataset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RasterCacheRecord",
        ),
    ]
