import { type ThemeConfig, theme } from "antd";

const appColors = {
  primary: "#2f7d62",
  primaryDark: "#225c52",
  pageBg: "#f4f8f5",
  siderBg: "#fbfdfb",
};

const workspaceColors = {
  text: "#dff8ee",
  textStrong: "#eafff8",
  textMuted: "rgba(223, 248, 238, 0.64)",
  textPlaceholder: "rgba(223, 248, 238, 0.5)",
  accent: "#74f3dd",
  accentMid: "#62ead7",
  accentSoft: "rgba(34, 197, 143, 0.16)",
  accentActive: "rgba(34, 197, 143, 0.22)",
  controlBg: "rgba(18, 58, 66, 0.58)",
  controlBgSubtle: "rgba(18, 58, 66, 0.34)",
  controlBgDisabled: "rgba(18, 58, 66, 0.22)",
  elevatedBg: "rgba(18, 58, 66, 0.94)",
  border: "rgba(111, 235, 226, 0.26)",
  borderSubtle: "rgba(111, 235, 226, 0.16)",
  borderHover: "rgba(116, 243, 221, 0.48)",
  outline: "rgba(116, 243, 221, 0.12)",
};

const workspaceInputTokens = {
  activeBg: workspaceColors.controlBg,
  activeBorderColor: workspaceColors.accent,
  activeShadow: `0 0 0 2px ${workspaceColors.outline}`,
  hoverBg: workspaceColors.controlBg,
  hoverBorderColor: workspaceColors.borderHover,
};

export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: appColors.primary,
    colorInfo: appColors.primary,
    borderRadius: 6,
    fontFamily: '"Avenir Next", "PingFang SC", "Microsoft YaHei", sans-serif',
  },
  components: {
    Button: { controlHeight: 34 },
    Card: { borderRadiusLG: 8 },
    Layout: {
      bodyBg: appColors.pageBg,
      headerBg: appColors.primaryDark,
      siderBg: appColors.siderBg,
    },
    Tabs: { itemSelectedColor: appColors.primary },
  },
};

export const workspacePanelTheme: ThemeConfig = {
  inherit: true,
  token: {
    colorPrimary: workspaceColors.accent,
    colorPrimaryHover: workspaceColors.textStrong,
    colorInfo: workspaceColors.accent,
    colorText: workspaceColors.text,
    colorTextBase: workspaceColors.text,
    colorTextSecondary: workspaceColors.textMuted,
    colorTextTertiary: "rgba(223, 248, 238, 0.48)",
    colorTextQuaternary: "rgba(223, 248, 238, 0.38)",
    colorTextDisabled: "rgba(223, 248, 238, 0.38)",
    colorTextPlaceholder: workspaceColors.textPlaceholder,
    colorBgContainer: workspaceColors.controlBg,
    colorBgContainerDisabled: workspaceColors.controlBgDisabled,
    colorBgElevated: workspaceColors.elevatedBg,
    colorBgTextHover: workspaceColors.accentSoft,
    colorBgTextActive: workspaceColors.accentActive,
    colorBorder: workspaceColors.border,
    colorBorderSecondary: workspaceColors.borderSubtle,
    controlItemBgHover: workspaceColors.accentSoft,
    controlItemBgActive: workspaceColors.accentActive,
    controlItemBgActiveHover: "rgba(34, 197, 143, 0.28)",
    controlOutline: workspaceColors.outline,
  },
  components: {
    Button: {
      colorPrimary: "rgba(34, 197, 143, 0.32)",
      colorPrimaryActive: "rgba(34, 197, 143, 0.48)",
      colorPrimaryHover: "rgba(34, 197, 143, 0.42)",
      colorTextLightSolid: workspaceColors.textStrong,
      defaultBg: workspaceColors.controlBgSubtle,
      defaultBorderColor: workspaceColors.border,
      defaultColor: workspaceColors.text,
      defaultHoverBg: workspaceColors.accentSoft,
      defaultHoverBorderColor: "rgba(116, 243, 221, 0.5)",
      defaultHoverColor: workspaceColors.textStrong,
      defaultActiveBg: workspaceColors.accentActive,
      defaultActiveBorderColor: workspaceColors.accent,
      defaultActiveColor: workspaceColors.textStrong,
      defaultGhostBorderColor: "rgba(116, 243, 221, 0.5)",
      defaultGhostColor: workspaceColors.accent,
      defaultShadow: "none",
      ghostBg: "rgba(18, 58, 66, 0.26)",
      primaryShadow: "none",
    },
    DatePicker: {
      ...workspaceInputTokens,
      cellHoverBg: workspaceColors.accentSoft,
      cellActiveWithRangeBg: workspaceColors.accentActive,
      cellHoverWithRangeBg: "rgba(34, 197, 143, 0.28)",
      cellRangeBorderColor: workspaceColors.accent,
      multipleItemBg: "rgba(18, 58, 66, 0.42)",
      multipleItemBorderColor: workspaceColors.border,
    },
    Descriptions: {
      contentColor: workspaceColors.text,
      extraColor: workspaceColors.textMuted,
      labelBg: "rgba(18, 58, 66, 0.42)",
      labelColor: workspaceColors.text,
      titleColor: workspaceColors.textStrong,
    },
    Dropdown: {
      colorBgElevated: workspaceColors.elevatedBg,
      colorText: workspaceColors.text,
      controlItemBgHover: workspaceColors.accentSoft,
      controlItemBgActive: workspaceColors.accentActive,
    },
    Empty: {
      colorTextDescription: "rgba(223, 248, 238, 0.58)",
    },
    Input: workspaceInputTokens,
    InputNumber: {
      ...workspaceInputTokens,
      handleActiveBg: workspaceColors.accentActive,
      handleBg: workspaceColors.controlBgSubtle,
      handleBorderColor: workspaceColors.borderSubtle,
      handleHoverColor: workspaceColors.accent,
    },
    Popover: {
      colorBgElevated: workspaceColors.elevatedBg,
      colorText: workspaceColors.text,
      zIndexPopup: 1070,
    },
    Segmented: {
      itemActiveBg: workspaceColors.accentSoft,
      itemColor: workspaceColors.textMuted,
      itemHoverBg: workspaceColors.accentSoft,
      itemHoverColor: workspaceColors.textStrong,
      itemSelectedBg: workspaceColors.controlBg,
      itemSelectedColor: workspaceColors.accent,
      trackBg: "rgba(18, 58, 66, 0.44)",
    },
    Select: {
      activeBorderColor: workspaceColors.accent,
      activeOutlineColor: workspaceColors.outline,
      clearBg: workspaceColors.controlBg,
      hoverBorderColor: workspaceColors.borderHover,
      multipleItemBg: "rgba(18, 58, 66, 0.42)",
      multipleItemBorderColor: workspaceColors.border,
      optionActiveBg: workspaceColors.accentSoft,
      optionSelectedBg: workspaceColors.accentActive,
      optionSelectedColor: workspaceColors.accent,
      selectorBg: workspaceColors.controlBg,
    },
    Slider: {
      dotActiveBorderColor: workspaceColors.accent,
      dotBorderColor: workspaceColors.border,
      handleActiveColor: workspaceColors.accent,
      handleActiveOutlineColor: workspaceColors.outline,
      handleColor: workspaceColors.accent,
      railBg: "rgba(95, 231, 221, 0.14)",
      railHoverBg: "rgba(95, 231, 221, 0.22)",
      trackBg: "rgba(116, 243, 221, 0.62)",
      trackHoverBg: workspaceColors.accent,
    },
    Tabs: {
      inkBarColor: workspaceColors.accentMid,
      itemActiveColor: workspaceColors.accent,
      itemColor: "rgba(223, 248, 238, 0.66)",
      itemHoverColor: workspaceColors.textStrong,
      itemSelectedColor: workspaceColors.accent,
    },
    Tag: {
      defaultBg: "rgba(18, 58, 66, 0.42)",
      defaultColor: workspaceColors.text,
      solidTextColor: workspaceColors.text,
    },
  },
};
