# Generated by Django 6.0.6 on 2026-06-28 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_dataresourcegroup_dataresource_inventory_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_code",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="字段编码"
                    ),
                ),
                ("name_cn", models.CharField(max_length=120, verbose_name="中文名")),
                (
                    "name_en",
                    models.CharField(blank=True, max_length=120, verbose_name="英文名"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=64, verbose_name="单位"),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="数据类型"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="字段类别"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="说明")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
            ],
            options={
                "verbose_name": "字段定义",
                "verbose_name_plural": "字段定义",
                "ordering": ("category", "field_code"),
            },
        ),
        migrations.CreateModel(
            name="ResourceDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain_type",
                    models.CharField(
                        choices=[
                            ("germplasm", "种质数据"),
                            ("genome", "基因组数据"),
                            ("individual", "个体数据"),
                            ("community", "群落数据"),
                            ("population", "种群数据"),
                            ("field_survey", "野外调查数据"),
                            ("remote_sensing", "遥感影像数据"),
                            ("molecular", "分子数据"),
                        ],
                        max_length=32,
                        verbose_name="业务数据类型",
                    ),
                ),
                (
                    "spatial_class",
                    models.CharField(
                        choices=[
                            ("spatial", "地理数据"),
                            ("non_spatial", "非地理数据"),
                            ("spatialized_table", "可空间化表格"),
                            ("derived_from_spatial", "由空间对象关联"),
                        ],
                        default="non_spatial",
                        max_length=32,
                        verbose_name="空间属性",
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("region", "区域"),
                            ("site", "地点"),
                            ("population", "种群"),
                            ("individual", "个体"),
                            ("plot", "样方/样点"),
                            ("observation", "观测记录"),
                            ("sample", "样品"),
                            ("molecular_assay", "分子实验"),
                            ("genome_file", "基因组文件"),
                            ("raster_scene", "遥感场景"),
                            ("raster_product", "遥感产品"),
                        ],
                        default="observation",
                        max_length=32,
                        verbose_name="数据粒度",
                    ),
                ),
                (
                    "standardization_status",
                    models.CharField(
                        choices=[
                            ("raw", "原始"),
                            ("profiled", "已预检"),
                            ("mapped", "已字段映射"),
                            ("spatialized", "已空间化"),
                            ("standardized", "已标准化"),
                            ("published", "已发布"),
                        ],
                        default="raw",
                        max_length=32,
                        verbose_name="标准化状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_profile",
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "资源业务分类",
                "verbose_name_plural": "资源业务分类",
            },
        ),
        migrations.CreateModel(
            name="SourceDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_file_name",
                    models.CharField(max_length=255, verbose_name="源文件名"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="文件哈希"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="提供单位"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="接收时间"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="源数据类型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_datasets",
                        to="catalog.dataresource",
                        verbose_name="关联资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "源数据集",
                "verbose_name_plural": "源数据集",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="SourceSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sheet_name",
                    models.CharField(max_length=160, verbose_name="小表名称"),
                ),
                (
                    "header_row",
                    models.PositiveIntegerField(default=1, verbose_name="表头行"),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(default=0, verbose_name="行数"),
                ),
                (
                    "column_count",
                    models.PositiveIntegerField(default=0, verbose_name="列数"),
                ),
                (
                    "detected_granularity",
                    models.CharField(
                        choices=[
                            ("region", "区域"),
                            ("site", "地点"),
                            ("population", "种群"),
                            ("individual", "个体"),
                            ("plot", "样方/样点"),
                            ("observation", "观测记录"),
                            ("sample", "样品"),
                            ("molecular_assay", "分子实验"),
                            ("genome_file", "基因组文件"),
                            ("raster_scene", "遥感场景"),
                            ("raster_product", "遥感产品"),
                        ],
                        default="observation",
                        max_length=32,
                        verbose_name="识别粒度",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sheets",
                        to="standards.sourcedataset",
                        verbose_name="源数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "源数据小表",
                "verbose_name_plural": "源数据小表",
            },
        ),
        migrations.CreateModel(
            name="SourceRecordLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(blank=True, max_length=120, verbose_name="表名"),
                ),
                ("row_key", models.CharField(max_length=120, verbose_name="源记录键")),
                (
                    "entity_type",
                    models.CharField(max_length=80, verbose_name="实体类型"),
                ),
                ("entity_id", models.PositiveBigIntegerField(verbose_name="实体 ID")),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_record_links",
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
                (
                    "source_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record_links",
                        to="standards.sourcesheet",
                        verbose_name="源数据小表",
                    ),
                ),
            ],
            options={
                "verbose_name": "源记录关联",
                "verbose_name_plural": "源记录关联",
            },
        ),
        migrations.CreateModel(
            name="SourceFieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_column",
                    models.CharField(max_length=160, verbose_name="源字段名"),
                ),
                (
                    "mapping_confidence",
                    models.FloatField(default=0, verbose_name="映射置信度"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="说明")),
                (
                    "field_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_mappings",
                        to="standards.fielddefinition",
                        verbose_name="标准字段",
                    ),
                ),
                (
                    "source_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="standards.sourcesheet",
                        verbose_name="源数据小表",
                    ),
                ),
            ],
            options={
                "verbose_name": "源字段映射",
                "verbose_name_plural": "源字段映射",
            },
        ),
        migrations.CreateModel(
            name="DataQualityIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_key",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="源记录键"
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(max_length=64, verbose_name="问题类型"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "提示"),
                            ("warning", "警告"),
                            ("error", "错误"),
                        ],
                        default="warning",
                        max_length=16,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "待处理"),
                            ("confirmed", "已确认"),
                            ("resolved", "已解决"),
                            ("ignored", "已忽略"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="处理状态",
                    ),
                ),
                ("message", models.TextField(verbose_name="问题说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_quality_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_issues",
                        to="catalog.dataresource",
                        verbose_name="数据资源",
                    ),
                ),
                (
                    "source_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quality_issues",
                        to="standards.sourcesheet",
                        verbose_name="源数据小表",
                    ),
                ),
            ],
            options={
                "verbose_name": "数据质量问题",
                "verbose_name_plural": "数据质量问题",
                "ordering": ("-created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="CoordinateParseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_key", models.CharField(max_length=120, verbose_name="源记录键")),
                (
                    "raw_longitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始经度"
                    ),
                ),
                (
                    "raw_latitude",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="原始纬度"
                    ),
                ),
                (
                    "parser",
                    models.CharField(blank=True, max_length=40, verbose_name="解析器"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="标准经度"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="标准纬度"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "有效"),
                            ("empty", "空值"),
                            ("invalid", "无效"),
                            ("out_of_range", "超出范围"),
                        ],
                        default="valid",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="说明")),
                (
                    "source_sheet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coordinate_records",
                        to="standards.sourcesheet",
                        verbose_name="源数据小表",
                    ),
                ),
            ],
            options={
                "verbose_name": "坐标解析记录",
                "verbose_name_plural": "坐标解析记录",
            },
        ),
        migrations.AddConstraint(
            model_name="sourcesheet",
            constraint=models.UniqueConstraint(
                fields=("dataset", "sheet_name"), name="uniq_source_dataset_sheet"
            ),
        ),
        migrations.AddIndex(
            model_name="sourcerecordlink",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="standards_s_entity__7a63cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcerecordlink",
            index=models.Index(
                fields=["source_sheet", "row_key"],
                name="standards_s_source__e82531_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcefieldmapping",
            constraint=models.UniqueConstraint(
                fields=("source_sheet", "source_column"),
                name="uniq_source_sheet_column_mapping",
            ),
        ),
        migrations.AddIndex(
            model_name="coordinateparserecord",
            index=models.Index(
                fields=["source_sheet", "row_key"],
                name="standards_c_source__d78f52_idx",
            ),
        ),
    ]
